In [ ]:
import pandas as pd
from pathlib import Path

# check root menu
root = Path.cwd()
print(root)

/workspaces/accounting1-task3/code/CAR

In [ ]:
# read in edgar csv

csv_path = Path("../../data/external/10k_word_counts.csv")

df = pd.read_csv(
    csv_path,
    dtype={"cik": str}      # make sure cik would not be read as integer
)
df.head()

,cik,name,tickers,exchanges,entity_type,sic,state_of_incorporation,filing_date,report_date,url,file_size_in_bytes,download_success,download_error,word_count
0,0000000020,K TRON INTERNATIONAL INC,NaN,NaN,operating,3823.0,NJ,2001-03-26,2000-12-30,https://www.sec.gov/Archives/edgar/data/20/000...,166846,True,NaN,16868.0
1,0000000020,K TRON INTERNATIONAL INC,NaN,NaN,operating,3823.0,NJ,2003-03-27,2002-12-28,https://www.sec.gov/Archives/edgar/data/20/000...,213998,True,NaN,23404.0
2,0000000020,K TRON INTERNATIONAL INC,NaN,NaN,operating,3823.0,NJ,2004-04-01,2004-01-03,https://www.sec.gov/Archives/edgar/data/20/000...,573844,True,NaN,28661.0
3,0000000020,K TRON INTERNATIONAL INC,NaN,NaN,operating,3823.0,NJ,2005-03-31,2005-01-01,https://www.sec.gov/Archives/edgar/data/20/000...,638337,True,NaN,29910.0
4,0000000020,K TRON INTERNATIONAL INC,NaN,NaN,operating,3823.0,NJ,2006-03-23,2005-12-31,https://www.sec.gov/Archives/edgar/data/20/000...,633855,True,NaN,30717.0

In [ ]:
# ensure cik to be 10-digit

df["cik"] = (
    df["cik"]
    .str.strip()
    .str.replace(r"\.0$", "", regex=True)
    .str.zfill(10)
)

df[["cik", "name"]].head()

          cik                      name
0  0000000020  K TRON INTERNATIONAL INC
1  0000000020  K TRON INTERNATIONAL INC
2  0000000020  K TRON INTERNATIONAL INC
3  0000000020  K TRON INTERNATIONAL INC
4  0000000020  K TRON INTERNATIONAL INC

In [7]:
# extract unique cik number

cik_list = (
    df["cik"]
    .dropna()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

print("Number of unique CIKs:", len(cik_list))
cik_list.head()

Number of unique CIKs: 33955

0    0000000020
1    0000001750
2    0000001800
3    0000001853
4    0000001923
Name: cik, dtype: str

In [8]:
# export cik number to csv

out_dir = Path("../../data/pulled")
out_dir.mkdir(exist_ok=True)

cik_list.to_frame(name="cik").to_csv(out_dir / "cik_list_all.csv", index=False)

with open(out_dir / "cik_list.txt", "w", encoding="utf-8") as f:
    for cik in cik_list:
        f.write(cik + "\n")